//! Authored outsider disagreement beats and choice presentation.

use super::*;

pub fn outsider_beat(outsider_id: &str, stage: u8) -> Option<OutsiderBeat> {
    match outsider_id {
        "veya_orn" => veya_orn_beat(stage),
        "sedge" => sedge_beat(stage),
        "ninth_voice_apart" => ninth_voice_apart_beat(stage),
        _ => None,
    }
}

fn veya_orn_beat(stage: u8) -> Option<OutsiderBeat> {
    match stage {
        0 => Some(OutsiderBeat {
                    outsider_id: "veya_orn",
                    outsider_name: "Veya Orn",
                    attention_faction: "directorate",
                    stage,
                    title: "TERMS FOR A BORROWED SHELTER",
                    description: "Veya will not sleep under a Directorate roof, but the cipher still opens doors that the refuge cannot afford to ignore.",
                    choices: [
                        OutsiderChoice {
                            id: "shelter_cipher",
                            label: "SHELTER THE CIPHER",
                            description: "Spend food to let Veya hide the useful parts. Mara learns the code can protect people.",
                            materials_cost: 0,
                            food_cost: 2,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -4,
                            relationship_partner: "mara_venn",
                            disagreement: true,
                            legacy_name: "Cipher Shelter",
                            legacy_stat: "accuracy",
                            legacy_amount: 2,
                        },
                        OutsiderChoice {
                            id: "open_ledger",
                            label: "OPEN THE LEDGER",
                            description: "Spend food to expose the whole route. Kira gets the truth, and the Directorate gets a signal.",
                            materials_cost: 0,
                            food_cost: 2,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: 3,
                            relationship_partner: "kira_voss",
                            disagreement: true,
                            legacy_name: "Open Ledger",
                            legacy_stat: "movement",
                            legacy_amount: 1,
                        },
                    ],
                }),
        1 => Some(OutsiderBeat {
                    outsider_id: "veya_orn",
                    outsider_name: "Veya Orn",
                    attention_faction: "directorate",
                    stage,
                    title: "THE RANGE BETWEEN THEM",
                    description: "The first operation proved Veya can read a Directorate line. The second question is who gets to decide where that line ends.",
                    choices: [
                        OutsiderChoice {
                            id: "mara_tests_range",
                            label: "MARA TESTS THE RANGE",
                            description: "Spend materials on a hard field test. Veya gains armour through a partnership built on challenge.",
                            materials_cost: 12,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -2,
                            relationship_partner: "mara_venn",
                            disagreement: true,
                            legacy_name: "Measured Range",
                            legacy_stat: "armour",
                            legacy_amount: 1,
                        },
                        OutsiderChoice {
                            id: "kira_walks_range",
                            label: "KIRA WALKS THE RANGE",
                            description: "Spend materials on a quiet survey. Veya gains damage through a partnership built on shared risk.",
                            materials_cost: 12,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: 2,
                            relationship_partner: "kira_voss",
                            disagreement: true,
                            legacy_name: "Walking Range",
                            legacy_stat: "damage",
                            legacy_amount: 1,
                        },
                    ],
                }),
        2 => Some(OutsiderBeat {
                    outsider_id: "veya_orn",
                    outsider_name: "Veya Orn",
                    attention_faction: "directorate",
                    stage,
                    title: "WHO KEEPS THE KEY",
                    description: "Veya has made the Waystation useful. The final decision is whether the cipher belongs to one person or to everyone who stayed to hear the argument.",
                    choices: [
                        OutsiderChoice {
                            id: "stay_on_line",
                            label: "STAY ON THE LINE",
                            description: "Keep the cipher close and make the Waystation answerable to its witnesses.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -2,
                            relationship_partner: "nadi_vale",
                            disagreement: false,
                            legacy_name: "Witnessed Line",
                            legacy_stat: "health",
                            legacy_amount: 1,
                        },
                        OutsiderChoice {
                            id: "share_the_key",
                            label: "SHARE THE KEY",
                            description: "Give the colony the whole cipher and accept that every open door can be opened from outside.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: 1,
                            relationship_partner: "sol_cairn",
                            disagreement: false,
                            legacy_name: "Shared Key",
                            legacy_stat: "accuracy",
                            legacy_amount: 1,
                        },
                    ],
                }),
        _ => None,
    }
}

fn sedge_beat(stage: u8) -> Option<OutsiderBeat> {
    match stage {
        0 => Some(OutsiderBeat {
                    outsider_id: "sedge",
                    outsider_name: "Sedge",
                    attention_faction: "brood",
                    stage,
                    title: "THE MAP IS NOT A SPECIMEN",
                    description: "Sedge brought a route-map in their body, and the Gene Lab wants a sample before the colony lets them rest.",
                    choices: [
                        OutsiderChoice {
                            id: "sedge_keep_map_personal",
                            label: "KEEP THE MAP PERSONAL",
                            description: "Spend food to give Sedge time before the lab asks. Nadi learns that a boundary can be a medical fact.",
                            materials_cost: 0,
                            food_cost: 2,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -4,
                            relationship_partner: "nadi_vale",
                            disagreement: true,
                            legacy_name: "Named Boundary",
                            legacy_stat: "health",
                            legacy_amount: 1,
                        },
                        OutsiderChoice {
                            id: "sedge_trade_the_route",
                            label: "TRADE THE ROUTE",
                            description: "Spend biomass to let Sol model the map. The colony gains a route, and the Brood learns it was copied.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 2,
                            attention_change: 3,
                            relationship_partner: "sol_cairn",
                            disagreement: true,
                            legacy_name: "Open Route",
                            legacy_stat: "movement",
                            legacy_amount: 1,
                        },
                    ],
                }),
        1 => Some(OutsiderBeat {
                    outsider_id: "sedge",
                    outsider_name: "Sedge",
                    attention_faction: "brood",
                    stage,
                    title: "WHAT THE MARSH OWES",
                    description: "The first operation proved Sedge can carry a route through danger. The next question is whether the colony can carry the responsibility back.",
                    choices: [
                        OutsiderChoice {
                            id: "sedge_draw_a_boundary",
                            label: "DRAW A BOUNDARY",
                            description: "Spend materials on a protected survey. Mara makes the route safer without claiming it belongs to the colony.",
                            materials_cost: 10,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -2,
                            relationship_partner: "mara_venn",
                            disagreement: true,
                            legacy_name: "Protected Route",
                            legacy_stat: "armour",
                            legacy_amount: 1,
                        },
                        OutsiderChoice {
                            id: "sedge_follow_the_pulse",
                            label: "FOLLOW THE PULSE",
                            description: "Spend biomass to let Ilya listen for the route's living signal instead of cutting it out of Sedge.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 2,
                            attention_change: 2,
                            relationship_partner: "ilya_reed",
                            disagreement: true,
                            legacy_name: "Living Signal",
                            legacy_stat: "damage",
                            legacy_amount: 1,
                        },
                    ],
                }),
        2 => Some(OutsiderBeat {
                    outsider_id: "sedge",
                    outsider_name: "Sedge",
                    attention_faction: "brood",
                    stage,
                    title: "A NAME THAT WALKS",
                    description: "Sedge has made the Gene Lab useful without letting it own the story. The final choice is who gets to carry the route into the future.",
                    choices: [
                        OutsiderChoice {
                            id: "sedge_keep_family_name",
                            label: "KEEP THE FAMILY NAME",
                            description: "Keep the route with Sedge's family record and make the Gene Lab answerable to the people it studies.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -2,
                            relationship_partner: "nadi_vale",
                            disagreement: false,
                            legacy_name: "Family Route",
                            legacy_stat: "health",
                            legacy_amount: 1,
                        },
                        OutsiderChoice {
                            id: "sedge_publish_the_route",
                            label: "PUBLISH THE ROUTE",
                            description: "Give every colony map the route and accept that shared knowledge can also become a beacon.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: 1,
                            relationship_partner: "kira_voss",
                            disagreement: false,
                            legacy_name: "Published Route",
                            legacy_stat: "accuracy",
                            legacy_amount: 1,
                        },
                    ],
                }),
        _ => None,
    }
}

fn ninth_voice_apart_beat(stage: u8) -> Option<OutsiderBeat> {
    match stage {
        0 => Some(OutsiderBeat {
                    outsider_id: "ninth_voice_apart",
                    outsider_name: "Ninth-Voice-Apart",
                    attention_faction: "brood",
                    stage,
                    title: "THE FIRST WORD IS BORROWED",
                    description: "Ninth repeats a phrase from the destroyed chorus. The colony must decide whether a borrowed voice is evidence, a warning, or a person asking for shelter.",
                    choices: [
                        OutsiderChoice {
                            id: "ninth_give_it_quiet",
                            label: "GIVE IT QUIET",
                            description: "Spend food to let Ninth choose a silence before the colony asks for a signal. Ilya learns that a voice can need shelter before it needs translation.",
                            materials_cost: 0,
                            food_cost: 2,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -4,
                            relationship_partner: "ilya_reed",
                            disagreement: true,
                            legacy_name: "Quiet Shelter",
                            legacy_stat: "health",
                            legacy_amount: 1,
                        },
                        OutsiderChoice {
                            id: "ninth_record_the_phrase",
                            label: "RECORD THE PHRASE",
                            description: "Spend biomass to preserve the borrowed command. Kira gets a warning, and the Brood gets proof that the voice survived.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 2,
                            attention_change: 3,
                            relationship_partner: "kira_voss",
                            disagreement: true,
                            legacy_name: "Recorded Echo",
                            legacy_stat: "accuracy",
                            legacy_amount: 1,
                        },
                    ],
                }),
        1 => Some(OutsiderBeat {
                    outsider_id: "ninth_voice_apart",
                    outsider_name: "Ninth-Voice-Apart",
                    attention_faction: "brood",
                    stage,
                    title: "WHAT THE CHORUS LEFT BEHIND",
                    description: "Ninth can anchor a hostile line, but every borrowed command leaves a trace. The colony decides whether to teach restraint or exploit the advantage.",
                    choices: [
                        OutsiderChoice {
                            id: "ninth_build_a_haven",
                            label: "BUILD A HAVEN",
                            description: "Spend materials on a quiet alcove beside the Gene Lab. Mara makes room for a body that cannot be reduced to a useful signal.",
                            materials_cost: 12,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -2,
                            relationship_partner: "mara_venn",
                            disagreement: true,
                            legacy_name: "Shelter Pattern",
                            legacy_stat: "armour",
                            legacy_amount: 1,
                        },
                        OutsiderChoice {
                            id: "ninth_open_the_channel",
                            label: "OPEN THE CHANNEL",
                            description: "Spend biomass to let Sol carry Ninth's resonance through the field relay. The colony gains force, and the Brood hears the invitation.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 2,
                            attention_change: 2,
                            relationship_partner: "sol_cairn",
                            disagreement: true,
                            legacy_name: "Open Resonance",
                            legacy_stat: "damage",
                            legacy_amount: 1,
                        },
                    ],
                }),
        2 => Some(OutsiderBeat {
                    outsider_id: "ninth_voice_apart",
                    outsider_name: "Ninth-Voice-Apart",
                    attention_faction: "brood",
                    stage,
                    title: "A VOICE WITH NO WITNESS",
                    description: "Ninth has learned three phrases the chorus never gave it. The final choice is whether its new voice belongs to the colony, the Brood, or the space between them.",
                    choices: [
                        OutsiderChoice {
                            id: "ninth_keep_the_gap",
                            label: "KEEP THE GAP",
                            description: "Keep the silence between borrowed phrases. Nadi records Ninth as a person who can refuse the chorus without becoming empty.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: -2,
                            relationship_partner: "nadi_vale",
                            disagreement: false,
                            legacy_name: "Kept the Gap",
                            legacy_stat: "health",
                            legacy_amount: 1,
                        },
                        OutsiderChoice {
                            id: "ninth_join_the_listeners",
                            label: "JOIN THE LISTENERS",
                            description: "Let Ninth sit with the colony's listening circle. The voice gains a future without pretending it has forgotten where it came from.",
                            materials_cost: 0,
                            food_cost: 0,
                            power_cost: 0,
                            biomass_cost: 0,
                            attention_change: 1,
                            relationship_partner: "kira_voss",
                            disagreement: false,
                            legacy_name: "Joined Listeners",
                            legacy_stat: "movement",
                            legacy_amount: 1,
                        },
                    ],
                }),
        _ => None,
    }
}
