//! State-changing intents emitted by immediate-mode screens.

use crate::colony::BuildingKind;
use macroquad_toolkit::grid::TilePos;

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum BattleLogFilter {
    #[default]
    All,
    Combat,
    Ground,
    System,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UiAction {
    StartMission,
    OpenMissionBriefing,
    SelectMission(String),
    CompleteResearch(String),
    ChooseContactProtocol(String),
    ChooseEscalationResponse(String),
    ChooseMirexisPath(String),
    ChooseMutationEvolution(String, String),
    ResolveCharacterEvent(String),
    RecruitOutsider,
    ResolveOutsiderBeat(u8, String),
    HostCommonsMeal,
    RunRelayScan,
    OpenSalvage,
    ProcessSalvage(crate::campaign::SalvageChoice),
    CloseSalvage,
    RunIdentityStewardship,
    PrepareIdentityBuilding,
    DeployMission,
    CycleFormation,
    ToggleDeployment(String),
    Continue,
    ReturnToTitle,
    ReturnToColony,
    OpenRoster,
    OpenGeneLab,
    SelectColonist(String),
    TrainSelected(String),
    LearnSelectedSkill(String),
    ToggleSelectedSkill(String),
    CraftSelected(String),
    SelectConstruction(BuildingKind),
    ConstructBuilding(BuildingKind, [i32; 2]),
    RepairBuilding(String),
    OpenFacilityUpgrade,
    QueueFacilityUpgrade(String, String),
    CloseFacilityUpgrade,
    TreatInjury,
    SelectTile(TilePos),
    SelectNextReady,
    MoveSelected(TilePos),
    AttackSelected(String),
    AttackCover(TilePos),
    InteractObjective,
    ActivateMutation,
    ActivateClassAction,
    ArmClassAction,
    UseClassActionOn(String),
    UseClassActionOnTile(TilePos),
    ActivateSkill(String),
    ArmSkill(String),
    UseSkillOn(String),
    UseSkillOnTile(TilePos),
    ArmEquipment(String),
    CancelTargeting,
    UseEquipmentOn(String),
    SetOverwatch,
    EndPhase,
    SkipPhaseReplay,
    ToggleTacticalHelp,
    ToggleBattleLog,
    SetBattleLogFilter(BattleLogFilter),
    AdvanceFirstHour,
    AcknowledgeColonist(String),
    ToggleFirstHourHelp,
    SkipFirstHourTutorial,
    RestartFirstHourTutorial,
    ChooseFirstHourInvestment(String),
    ToggleSettings,
    ToggleFieldNotes,
    ToggleMemorial,
    PreviousMemorialPage,
    NextMemorialPage,
    SelectFieldNote(usize),
    AudioVolumeDown,
    AudioVolumeUp,
    ToggleMute,
    ToggleReducedMotion,
    Save,
    Load,
    DeleteSave,
}
