//! State-changing intents emitted by immediate-mode screens.

use crate::colony::BuildingKind;
use macroquad_toolkit::grid::TilePos;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UiAction {
    StartMission,
    OpenMissionBriefing,
    SelectMission(String),
    CompleteResearch(String),
    ChooseContactProtocol(String),
    ChooseEscalationResponse(String),
    ChooseMirexisPath(String),
    ChooseMutationEvolution(String, String),
    ResolveCharacterEvent(String),
    DeployMission,
    CycleFormation,
    ToggleDeployment(String),
    Continue,
    ReturnToTitle,
    ReturnToColony,
    OpenRoster,
    OpenGeneLab,
    SelectColonist(String),
    TrainSelected(String),
    CraftSelected(String),
    SelectConstruction(BuildingKind),
    ConstructBuilding(BuildingKind, [i32; 2]),
    RepairBuilding(String),
    TreatInjury,
    SelectTile(TilePos),
    SelectNextReady,
    MoveSelected(TilePos),
    AttackSelected(String),
    AttackCover(TilePos),
    InteractObjective,
    ActivateMutation,
    ActivateClassAction,
    ArmClassAction,
    UseClassActionOn(String),
    ArmEquipment(String),
    CancelTargeting,
    UseEquipmentOn(String),
    SetOverwatch,
    EndPhase,
    SkipPhaseReplay,
    ToggleTacticalHelp,
    ToggleBattleLog,
    AdvanceFirstHour,
    AcknowledgeColonist(String),
    ToggleFirstHourHelp,
    SkipFirstHourTutorial,
    RestartFirstHourTutorial,
    ChooseFirstHourInvestment(String),
    ToggleSettings,
    AudioVolumeDown,
    AudioVolumeUp,
    ToggleMute,
    ToggleReducedMotion,
    Save,
    Load,
    DeleteSave,
}
